name: Foundry Coverage

on:
  pull_request:
  push:
    branches: [main]
jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dao-smartcontract
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run coverage
        run: forge coverage --skip 'src/mocks/**' --skip 'src/script/**' --skip 'src/deploy/**' --ir-minimum --report lcov  > lcov.info

      - name: Upload filtered coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
